### ISSUE TITLE
@change event is triggered when the component loads

### ISSUE THREAD

**Issue by sanifhimani** [vueform/toggle#1]
Hi @adamberecz. Thanks for you amazing work here!
I've added the toggle in my design which has tabs to change the views. When the view that has the toggle loads, it triggers the change event. I'm not sure if it is supposed to do this, or only trigger when it's changed and not rendered for the first time. I've attached some screenshots to explain better.

Image for First tab with nothing in the console
<img width="1660" alt="Screen Shot 2021-04-07 at 10 43 19 PM" src="https://user-images.githubusercontent.com/25054137/113960557-a9b4a480-97f2-11eb-9537-19923fa4cf71.png">

Image of setting tab with the change event triggered without clicking the toggle.
<img width="1660" alt="Screen Shot 2021-04-07 at 10 44 49 PM" src="https://user-images.githubusercontent.com/25054137/113960719-e1bbe780-97f2-11eb-81b2-6e5697a97f18.png">

Is there anything that needs to be done or does it work this way?

**Comment by adamberecz** [comment]
Resolved in `2.0.0`.
