### ISSUE TITLE
VitePress warning about package not written in CJS

### ISSUE THREAD

**Issue by staghouse** [vueform/toggle#10]
I am using this package in a VitePress setup i have and during build time I am alerted to this warning:

`@vueform/toggle doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix
`

It does not seem to be breaking anything but just wanted to point it out incase this is a fix that should take place.

**Comment by staghouse** [comment]
This is now breaking in the latest version of VitePress

**Comment by adamberecz** [comment]
Feel free to reopen with a reproducible example if still relevant.
