### ISSUE TITLE
Demo is not Working

### ISSUE THREAD

**Issue by hos1992** [vueform/toggle#11]

**Comment by CreativeWarlock** [comment]
Yep, that's still the case:

"[Vue warn]: Unhandled error during execution of render function", "
", " at &lt;Toggle", "modelValue=false", "onUpdate:modelValue=fn&lt;onUpdate:modelValue&gt;", "value=false", "&gt;", "
", " at &lt;App&gt;"
"Script error."

**Comment by adamberecz** [comment]
Thanks - fixed.
