### ISSUE TITLE
Handle size stays the same after changing the height of the toggle

### ISSUE THREAD

**Issue by BKirev** [vueform/toggle#4]
After using ```--toggle-width: 120px``` and ```--toggle-height: 35px``` for example, the handle will stay 20x20 pixels. The width and height of the handle should be added as variables as well.

**Comment by cwoodward10** [comment]
I had this same issue too. Was trying to find a way to hack it with css selectors but haven't yet.

**Comment by adamberecz** [comment]
Fixed.
