### ISSUE TITLE
@change is triggered on load when given a value

### ISSUE THREAD

**Issue by xLink** [vueform/toggle#9]
I've already seen #1 and #2, but this does seem to still be happening.
I tried the is mounted fix, and that didnt stop it. 
Do we know why this is happening or a workaround?

**Comment by Martinretrou** [comment]
This issue is still present in `2.0.2`, the `@change` event is triggered when the v-model is passed down to the toggle component.

**Comment by adamberecz** [comment]
This should only happen if the model value does not equal to `trueValue` or `falseValue`. If you experience otherwise feel free to reopen.
